interface IMappingkItem {
	cn: string
	en: string[]
	synonyms?: string[]
}
interface IMappingData {
	[key: string]: IMappingkItem
}

const mappingData: IMappingData = {
    创建: {
        cn: '创建',
        en: ['create', 'creation'],
        synonyms: ['新建'],
    },
    删除: {
        cn: '删除',
        en: ['detele', 'drop', 'remove'],
    },
    新建: {
        cn: '新建',
        en: ['new'],
        synonyms: ['创建'],
    },
    退出: { cn: '退出', en: ['abort', 'quit'] },
    抽象: { cn: '抽象', en: ['abstract'] },
    确认: { cn: '确认', en: ['acknowledge', 'confirm'] },
    接受: { cn: '接受', en: ['accept'] },
    适配器: { cn: '适配器', en: ['adapter'] },
    别名: { cn: '别名', en: ['alias'] },
    箭头: { cn: '箭头', en: ['arrow'] },
    赋值: { cn: '赋值', en: ['assign'] },
    异步: { cn: '异步', en: ['asynchronous'] },
    尝试: { cn: '尝试', en: ['attempt'] },
    连接: { cn: '连接', en: ['attach'] },
    授权: { cn: '授权', en: ['authorize'] },
    认证: { cn: '认证', en: ['authenticate'] },
    自动: { cn: '自动', en: ['automatic'] },
    平均: { cn: '平均', en: ['average'] },
    行为: { cn: '行为', en: ['behavior'] },
    启动: { cn: '启动', en: ['boot'] },
    引导程序: { cn: '引导程序', en: ['bootstrap'] },
    桥: { cn: '桥', en: ['bridge'] },
    广播: { cn: '广播', en: ['broadcast'] },
    浏览器: { cn: '浏览器', en: ['browser'] },
    边界: { cn: '边界', en: ['bound'] },
    捕获: { cn: '捕获', en: ['catch', 'capture'] },
    类别: { cn: '类别', en: ['category', 'classification'] },
    原因: { cn: '原因', en: ['reason'] },
    证书: { cn: '证书', en: ['certificate'] },
    字符集: { cn: '字符集', en: ['charset'] },
    图表: { cn: '图表', en: ['chart'] },
    覆盖: { cn: '覆盖', en: ['cover'] },
    列: { cn: '列', en: ['column'] },
    命令: { cn: '命令', en: ['command'] },
    指令: { cn: '指令', en: ['command'] },
    提交: { cn: '提交', en: ['commit'] },
    评论: { cn: '评论', en: ['comment'] },
    对比: { cn: '对比', en: ['compare'] },
    编译: { cn: '编译', en: ['compile'] },
    组成: { cn: '组成', en: ['compose'] },
    组件: { cn: '组件', en: ['component'] },
    完成: { cn: '完成', en: ['complete'] },
    压缩: { cn: '压缩', en: ['compress'] },
    约束: { cn: '约束', en: ['constraint'] },
    冲突: { cn: '冲突', en: ['conflict'] },
    构造函数: { cn: '构造函数', en: ['constructor'] },
    构造器: { cn: '构造器', en: ['constructor'] },
    上下文: { cn: '上下文', en: ['context'] },
    包含: { cn: '包含', en: ['contain'] },
    变换: { cn: '变换', en: ['convert'] },
    装饰: { cn: '装饰', en: ['decoration'] },
    依赖: { cn: '依赖', en: ['dependencies'] },
    定义: { cn: '定义', en: ['define'] },
    延迟: { cn: '延迟', en: ['defer'] },
    声明: { cn: '声明', en: ['declare', 'statement'] },
    装饰者: { cn: '装饰者', en: ['decorator'] },
    设备: { cn: '设备', en: ['device'] },
    分发: { cn: '分发', en: ['distribute'] },
    驱动: { cn: '驱动', en: ['drive'] },
    文档: { cn: '文档', en: ['document'] },
    明确地: { cn: '明确地', en: ['explicitly'] },
    影响: { cn: '影响', en: ['effect'] },
    高效: { cn: '高效', en: ['efficient'] },
    模拟器: { cn: '模拟器', en: ['emulator'] },
    执行: { cn: '执行', en: ['perform'] },
    探索: { cn: '探索', en: ['explore'] },
    估价: { cn: '估价', en: ['evaluate'] },
    输出: { cn: '输出', en: ['export', 'output'] },
    暴露: { cn: '暴露', en: ['expose'] },
    表达式: { cn: '表达式', en: ['expression'] },
    提取: { cn: '提取', en: ['extract'] },
    继承: { cn: '继承', en: ['extends'] },
    电子: { cn: '电子', en: ['electron'] },
    评估: { cn: '评估', en: ['evaluate'] },
    说明: { cn: '说明', en: ['explain'] },
    发射: { cn: '发射', en: ['emit'] },
    表情: { cn: '表情', en: ['emoji'] },
    禁止: { cn: '禁止', en: ['forbid'] },
    伪造: { cn: '伪造', en: ['forgery'] },
    片段: { cn: '片段', en: ['fragment', 'snippet'] },
    网关: { cn: '网关', en: ['gateway'] },
    生成: { cn: '生成', en: ['generate'] },
    图形: { cn: '图形', en: ['graph'] },
    处理: { cn: '处理', en: ['handle'] },
    水平: { cn: '水平', en: ['horizontal'] },
    小时: { cn: '小时', en: ['hour'] },
    高亮: { cn: '高亮', en: ['highlight'] },
    混合: { cn: '混合', en: ['hybrid'] },
    标识符: { cn: '标识符', en: ['identifier'] },
    迭代器: { cn: '迭代器', en: ['iterator'] },
    不可变的: { cn: '不可变的', en: ['immutable'] },
    导入: { cn: '导入', en: ['import'] },
    实现: { cn: '实现', en: ['implement'] },
    增加: { cn: '增加', en: ['increase'] },
    增量: { cn: '增量', en: ['increment'] },
    索引: { cn: '索引', en: ['index'] },
    注入: { cn: '注入', en: ['inject'] },
    实例: { cn: '实例', en: ['instance'] },
    整数: { cn: '整数', en: ['integer'] },
    交互: { cn: '交互', en: ['interaction'] },
    接口: { cn: '接口', en: ['interface'] },
    检查: { cn: '检查', en: ['inspect'] },
    信息: { cn: '信息', en: ['information'] },
    调用: { cn: '调用', en: ['invoke'] },
    问题: { cn: '问题', en: ['issue'] },
    最新: { cn: '最新', en: ['latest'] },
    逻辑: { cn: '逻辑', en: ['logic'] },
    清单: { cn: '清单', en: ['manifest'] },
    匹配: { cn: '匹配', en: ['match'] },
    矩阵: { cn: '矩阵', en: ['matrix'] },
    方法: { cn: '方法', en: ['method'] },
    元: { cn: '元', en: ['meta'] },
    模型: { cn: '模型', en: ['model'] },
    模块: { cn: '模块', en: ['module'] },
    主要的: { cn: '主要的', en: ['major'] },
    次要的: { cn: '次要的', en: ['minor'] },
    手册: { cn: '手册', en: ['manual'] },
    指南: { cn: '指南', en: ['manual'] },
    监控: { cn: '监控', en: ['monitor'] },
    突变: { cn: '突变', en: ['mutation'] },
    多: { cn: '多', en: ['multiple'] },
    中间件: { cn: '中间件', en: ['middleware'] },
    分钟: { cn: '分钟', en: ['minute'] },
    观察者: { cn: '观察者', en: ['observer'] },
    操作者: { cn: '操作者', en: ['operator'] },
    所有者: { cn: '所有者', en: ['owner'] },
    包: { cn: '包', en: ['package'] },
    分页: { cn: '分页', en: ['pagination'] },
    绘制: { cn: '绘制', en: ['paint'] },
    渲染: { cn: '渲染', en: ['render'] },
    参数: { cn: '参数', en: ['parameter'] },
    模式: { cn: '模式', en: ['pattern'] },
    性能: { cn: '性能', en: ['performance'] },
    权限: { cn: '权限', en: ['permission'] },
    平台: { cn: '平台', en: ['platform'] },
    阶段: { cn: '阶段', en: ['stage'] },
    前缀: { cn: '前缀', en: ['prefix'] },
    现在的: { cn: '现在的', en: ['present'] },
    保护: { cn: '保护', en: ['protect'] },
    原型: { cn: '原型', en: ['prototype'] },
    程序: { cn: '程序', en: ['program'] },
    进程: { cn: '进程', en: ['process'] },
    进展: { cn: '进展', en: ['progress'] },
    承诺: { cn: '承诺', en: ['promise'] },
    临时的: { cn: '临时的', en: ['provisional'] },
    预设: { cn: '预设', en: ['preset'] },
    前置: { cn: '前置', en: ['prepend'] },
    精确: { cn: '精确', en: ['precision'] },
    精简: { cn: '精简', en: ['prune'] },
    原始的: { cn: '原始的', en: ['primitive'] },
    补丁: { cn: '补丁', en: ['polyfill'] },
    扼要: { cn: '扼要', en: ['profile'] },
    协议: { cn: '协议', en: ['protocol'] },
    端口: { cn: '端口', en: ['port'] },
    提供: { cn: '提供', en: ['provide'] },
    优先: { cn: '优先', en: ['priority'] },
    私有的: { cn: '私有的', en: ['private'] },
    公用: { cn: '公用', en: ['public'] },
    发布: { cn: '发布', en: ['publish'] },
    查询: { cn: '查询', en: ['query'] },
    队列: { cn: '队列', en: ['queue'] },
    响应: { cn: '响应', en: ['reactive'] },
    记录: { cn: '记录', en: ['record'] },
    矩形: { cn: '矩形', en: ['rectangle/rect'] },
    引用: { cn: '引用', en: ['reference'] },
    正则: { cn: '正则', en: ['regular'] },
    解决: { cn: '解决', en: ['resolve'] },
    拒绝: { cn: '拒绝', en: ['reject'] },
    报告: { cn: '报告', en: ['report'] },
    有关: { cn: '有关', en: ['related'] },
    版本: { cn: '版本', en: ['release'] },
    路由: { cn: '路由', en: ['route'] },
    脚手架: { cn: '脚手架', en: ['scaffold'] },
    秒: { cn: '秒', en: ['second'] },
    安全: { cn: '安全', en: ['secure'] },
    口号: { cn: '口号', en: ['slogan'] },
    语法: { cn: '语法', en: ['syntax'] },
    规范: { cn: '规范', en: ['specification'] },
    指定: { cn: '指定', en: ['specify'] },
    稳定: { cn: '稳定', en: ['stable'] },
    状态: { cn: '状态', en: ['state', 'status'] },
    栈: { cn: '栈', en: ['stack'] },
    结构: { cn: '结构', en: ['structure'] },
    工作室: { cn: '工作室', en: ['studio'] },
    相似: { cn: '相似', en: ['similar'] },
    子类: { cn: '子类', en: ['subclass'] },
    订阅: { cn: '订阅', en: ['subscribe'] },
    粘的: { cn: '粘的', en: ['sticky'] },
    垫片: { cn: '垫片', en: ['shim'] },
    任务: { cn: '任务', en: ['task'] },
    遍历: { cn: '遍历', en: ['traversal'] },
    临时: { cn: '临时', en: ['temporary'] },
    终端: { cn: '终端', en: ['terminal'] },
    追踪: { cn: '追踪', en: ['track'] },
    教程: { cn: '教程', en: ['tutorial'] },
    升级: { cn: '升级', en: ['upgrade'] },
    唯一的: { cn: '唯一的', en: ['unique'] },
    垂直: { cn: '垂直', en: ['vertical'] },
    供应商: { cn: '供应商', en: ['vendors'] },
    通过: { cn: '通过', en: ['via'] },
    空的: { cn: '空的', en: ['void'] },
    虚拟的: { cn: '虚拟的', en: ['virtual'] },
    小部件: { cn: '小部件', en: ['widget'] },
    通配符: { cn: '通配符', en: ['wildcard'] },
    包装: { cn: '包装', en: ['wrap'] },
}

export default mappingData
